server:
  port: 8080
  #servlet: 
    #context-path: /ecard
spring: 
  #profiles:
  #  active: dev
  application:
    name: equityPosition
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8   
  datasource:
    #url: jdbc:h2:~/test
    url: jdbc:h2:mem:test #配置h2数据库的连接地址
    #schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    #data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
    #指定sql映射文件位置
#    mapper-locations: classpath*:mapper/*.xml
logging:
  file:
    name: ./logs/equityPosition.log
    max-size: 30MB
    max-history: 10
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    #com.erwei: DEBUG
